name: nextjs-monorepo-example-db-main-prisma-e2e-postgresql
services:
  e2e-postgres:
    container_name: db-main-prisma-e2e-postgresql
    image: postgres:15-alpine
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
    environment:
      - POSTGRES_DB=e2edb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 2s
      timeout: 5s
      retries: 5
    #volumes:
    # Do not persist volumes for e2e
    #- e2e_db_data:/var/lib/postgresql/data:rw
#volumes:
#e2e_db_data:
